#!/bin/bash
pip install jupyterlab
jupyter labextension install @jupyter-widgets/jupyterlab-manager
pip install jupyter_contrib_nbextensions
jupyter contrib nbextension install --user
jupyter nbextension enable --py widgetsnbextension
#jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.38 --minimize=False
